### ISSUE TITLE
Coin flip simulation and a couple of independent simulations do not agree

### ISSUE THREAD

**Issue by tzs** [the-pudding/country-radio-data#1]
A couple of people on the "Hacker News" discussion of your article wrote their own simulations, and got a much lower number of expected back-to-back female plays than your simulation got.

As of right now, these simulations are in this thread there: https://news.ycombinator.com/item?id=36065113

In particular, my simulation got that if 11% of the songs played are by females, then the number of songs by females that are played back-to-back after another song be a female should be about 1.23% of plays, which matches the other simulation on HN, and matches the radio station data in your article.

If p is the probability that a song is by a female, it looks like somewhere you have dropped a factor of p. The number of back-to-back female songs, according to my simulation, should be about N p^2 where N is the total number of songs, but you seem to be getting N p.

**Comment by jadiehm** [comment]
@tzs 

Thanks so much for the flag! Y’all were absolutely right that something wonky was going on. I’ve since made adjustments and updated the piece with a correction.   

The visual and accompanying text were using the number of all women plays, not just the back-to-back ones. , but the underlying simulation calculations were correct. 

It’s more likely that the simulation back-to-back numbers would fall between 7—17 a day NOT the originally stated 30–40. For the particular station in the intro, San Antonio (KCYY-FM), the number of women’s back-to-back plays that they actually played isn’t completely outside of the realm of possibilities if left up to chance, but we would be more likely to see higher numbers. For 17 other stations, the observed numbers do fall outside the simulation distribution. (See the histograms in the methodology section. Note that they are for the full 19 days.)  

Thank you again for raising this issue and for being so kind and thoughtful with your explanation — it’s rare on the internet these days! I’ll follow up in the HN thread as well.
